library_judge_math:
  resources_servers:
    library_judge_math:
      entrypoint: app.py
      judge_model_server:
        type: responses_api_models
        name: ???
      judge_responses_create_params: {
        input: []
      }
      should_use_judge: false
      domain: math
      verified: false
library_judge_math_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: library_judge_math
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: validation
        type: validation
        jsonl_fpath: resources_servers/library_judge_math/data/dapo17k_trajectory_collection_train.jsonl
        gitlab_identifier:
          dataset_name: dapo17k
          version: 0.0.1
          artifact_fpath: dapo17k_train.jsonl
        num_repeats: 16
        license: Apache 2.0
