library_judge_math:
  resources_servers:
    library_judge_math:
      entrypoint: app.py
      judge_model_server:
        type: responses_api_models
        name: ???
      judge_responses_create_params: {
        input: []
      }
      should_use_judge: true
library_judge_math_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: library_judge_math
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/library_judge_math/data/train.jsonl
        gitlab_identifier:
          dataset_name: math_open_math_reasoning
          version: 0.0.1
          artifact_fpath: open_math_reasoning_problems.jsonl
        license: Apache 2.0
      - name: validation
        type: validation
        jsonl_fpath: resources_servers/library_judge_math/data/aime24_validation.jsonl
        gitlab_identifier:
          dataset_name: aime24
          version: 0.0.1
          artifact_fpath: aime24.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/library_judge_math/data/example.jsonl
