multiverse_math_hard:
  resources_servers:
    multiverse_math_hard:
      entrypoint: app.py
      domain: agent
      verified: false
multiverse_math_hard_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: multiverse_math_hard
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
        - name: train
          type: train
          jsonl_fpath: resources_servers/multiverse_math_hard/data/train.jsonl
          gitlab_identifier:
            dataset_name: multiverse_math_hard
            version: 0.0.1
            artifact_fpath: train.jsonl
          license: Apache 2.0
        - name: example
          type: example
          jsonl_fpath: resources_servers/multiverse_math_hard/data/example.jsonl
